// submissions/matheus-petrato/frontend/src/lib/components/blocks/Sidebar.svelte
<script lang="ts">
	import { Database, LayoutDashboard, Settings, MessageSquare, Plus } from 'lucide-svelte';
	import { onMount } from 'svelte';
	import { api, type DataSource } from '$lib/services/api';

	let sources = $state<DataSource[]>([]);
	let loading = $state(true);

	onMount(async () => {
		try {
			sources = await api.datasources.list();
		} catch (err) {
			console.error("Erro ao carregar fontes:", err);
		} finally {
			loading = false;
		}
	});
</script>

<aside class="w-64 border-r border-sidebar-border bg-sidebar text-sidebar-foreground h-screen flex flex-col">
	<div class="h-16 flex items-center px-6 border-b border-sidebar-border">
		<img src="/logo-full.svg" alt="G4 Compass" class="h-7 w-auto" />
	</div>

	<div class="flex-1 overflow-y-auto p-4 space-y-6">
		<!-- Menu Principal -->
		<div class="space-y-1">
			<button class="w-full flex items-center gap-3 px-3 py-2 rounded-lg bg-sidebar-accent text-sidebar-foreground font-medium transition-colors border border-sidebar-border">
				<MessageSquare class="w-4 h-4 text-primary" />
				Compass
			</button>
			<button class="w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sidebar-foreground/70 hover:bg-sidebar-accent/70 hover:text-sidebar-foreground transition-colors">
				<LayoutDashboard class="w-4 h-4" />
				Pipeline
			</button>
		</div>

		<!-- Data Sources -->
		<div>
			<div class="flex items-center justify-between px-3 mb-2">
				<span class="text-xs font-semibold text-sidebar-foreground/60 uppercase tracking-wider">Fontes de Dados</span>
				<a href="/settings/sources" class="text-sidebar-foreground/60 hover:text-primary transition-colors">
					<Plus class="w-4 h-4" />
				</a>
			</div>
			<div class="space-y-1">
				{#if loading}
					<div class="px-3 py-2 space-y-3">
						<div class="h-4 bg-sidebar-accent animate-pulse rounded w-3/4"></div>
						<div class="h-4 bg-sidebar-accent animate-pulse rounded w-1/2"></div>
					</div>
				{:else if sources.length === 0}
					<p class="px-3 py-2 text-xs text-sidebar-foreground/60 italic">Nenhuma fonte conectada</p>
				{:else}
					{#each sources as source}
						<button class="w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition-all group {source.is_active ? 'bg-sidebar-accent text-sidebar-foreground' : 'text-sidebar-foreground/70 hover:bg-sidebar-accent/70 hover:text-sidebar-foreground'}">
							<Database class="w-4 h-4 {source.is_active ? 'text-primary' : 'text-sidebar-foreground/60 group-hover:text-sidebar-foreground'}" />
							<span class="truncate">{source.name}</span>
							{#if source.is_active}
								<div class="w-1.5 h-1.5 rounded-full bg-primary ml-auto shadow-[0_0_8px_rgba(196,149,42,0.6)] opacity-80"></div>
							{/if}
						</button>
					{/each}
				{/if}
			</div>
		</div>
	</div>

	<div class="p-4 border-t border-sidebar-border">
		<a href="/settings/sources" class="w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sidebar-foreground/70 hover:bg-sidebar-accent/70 hover:text-sidebar-foreground transition-colors">
			<Settings class="w-4 h-4" />
			Configurações
		</a>
	</div>
</aside>

// submissions/marcio-ferreira-portamento/solution/frontend/src/components/Sidebar.tsx
import React from 'react';
import { Home, PieChart, Users, Settings, LogOut, Briefcase } from 'lucide-react';

export default function Sidebar() {
  return (
    <div className="w-64 bg-white border-r border-gray-200 h-screen fixed left-0 top-0 flex flex-col items-center py-6 shadow-sm z-50">
      {/* Logo */}
      <div className="mb-10 w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold text-xl shadow-md">
        P
      </div>

      {/* Navigation */}
      <nav className="flex flex-col gap-4 w-full px-4">
        <button className="flex items-center gap-3 px-4 py-3 bg-blue-50 text-blue-700 rounded-xl font-semibold transition-colors">
          <PieChart size={20} />
          <span>Dashboard</span>
        </button>
        <button className="flex items-center gap-3 px-4 py-3 text-gray-500 hover:bg-gray-50 hover:text-gray-900 rounded-xl font-medium transition-colors">
          <Briefcase size={20} />
          <span>Oportunidades</span>
        </button>
        <button className="flex items-center gap-3 px-4 py-3 text-gray-500 hover:bg-gray-50 hover:text-gray-900 rounded-xl font-medium transition-colors">
          <Users size={20} />
          <span>Equipe</span>
        </button>
      </nav>

      <div className="mt-auto flex flex-col w-full px-4 gap-2">
        <button className="flex items-center gap-3 px-4 py-3 text-gray-500 hover:bg-gray-50 hover:text-gray-900 rounded-xl font-medium transition-colors">
          <Settings size={20} />
          <span>Configurações</span>
        </button>
        <div className="w-full border-t border-gray-100 my-2"></div>
        <div className="flex items-center gap-3 px-4 py-2 mt-2">
          <div className="w-10 h-10 bg-gray-200 rounded-full overflow-hidden">
            <img src="https://i.pravatar.cc/150?u=a042581f4e29026704d" alt="User" />
          </div>
          <div className="flex flex-col text-sm">
            <span className="font-bold text-gray-800">Darcel S.</span>
            <span className="text-gray-400 text-xs">Vendas G4</span>
          </div>
        </div>
      </div>
    </div>
  );
}
