// submissions/matheus-petrato/frontend/src/routes/(auth)/login/+page.svelte
<script lang="ts">
  import { api, setStoredToken, setStoredUser } from '$lib/services/api';

  let email = $state('');
  let password = $state('');
  let loading = $state(false);
  let errorMessage = $state('');

  async function handleLogin(e: Event) {
    e.preventDefault();
    loading = true;
    errorMessage = '';

    try {
      const data = await api.auth.login({ email, password });
      setStoredToken(data.token);
      setStoredUser(data.user);
      
      // Redirect to main app chat
      window.location.href = '/';
      
    } catch (err: any) {
      errorMessage = err.message || 'Erro ao conectar no servidor.';
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex flex-col animate-in fade-in slide-in-from-bottom-4 duration-500">
  <h1 class="text-[32px] mb-2 font-semibold tracking-tight text-foreground">Log in</h1>
  <p class="text-muted-foreground mb-8">Acesse com as credenciais enviadas por email.</p>

  {#if errorMessage}
    <div class="bg-red-500/10 border border-red-500/50 text-red-600 text-sm p-3 rounded-lg mb-4">
      {errorMessage}
    </div>
  {/if}

  <form class="flex flex-col gap-4" onsubmit={handleLogin}>
    <!-- Email -->
    <div class="space-y-1.5 flex flex-col">
      <label for="email" class="text-[14px] font-medium text-foreground">Email</label>
      <input id="email" type="email" bind:value={email} required placeholder="nome@empresa.com" class="w-full px-3 py-2.5 rounded-lg border border-border bg-background shadow-sm hover:border-primary/50 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all text-sm placeholder:text-muted-foreground/60" />
    </div>

    <!-- Password -->
    <div class="space-y-1.5 flex flex-col">
      <label for="password" class="text-[14px] font-medium text-foreground">Senha</label>
      <input id="password" type="password" bind:value={password} required placeholder="••••••••" class="w-full px-3 py-2.5 rounded-lg border border-border bg-background shadow-sm hover:border-primary/50 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all text-sm placeholder:text-muted-foreground/60" />
    </div>

    <!-- Options -->
    <div class="flex items-center justify-between mt-1 mb-2">
      <div class="flex items-center gap-2">
        <input type="checkbox" id="remember" class="rounded-[4px] border border-border text-primary focus:ring-1 focus:ring-primary/50 w-4 h-4 cursor-pointer accent-primary" />
        <label for="remember" class="text-sm text-foreground font-medium cursor-pointer">Lembrar por 30 dias</label>
      </div>
      <button type="button" class="text-sm font-semibold text-primary hover:text-primary/80 transition-colors">
        Esqueceu a senha?
      </button>
    </div>

    <button type="submit" disabled={loading} class="w-full py-2.5 rounded-lg bg-primary hover:bg-opacity-90 active:scale-[0.98] text-primary-foreground text-[15px] font-medium transition-all shadow-sm shadow-primary/30 mt-2 disabled:opacity-70 disabled:cursor-not-allowed">
      {loading ? 'Entrando...' : 'Entrar'}
    </button>
  </form>

  <p class="text-center text-sm text-muted-foreground mt-8">
    Precisa de acesso? <a href="mailto:help@g4compass.com" class="text-primary font-semibold hover:underline transition-colors">Fale com seu gestor</a>
  </p>
</div>

// client/src/pages/login.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/context/auth";

export default function Login() {
  const [, setLocation] = useLocation();
  const { login } = useAuth();
  const [email, setEmail] = useState("admin@hermes.io");
  const [password, setPassword] = useState("hermes123");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const user = await login(email, password);
      setLocation(user.role === "admin" ? "/admin" : "/meus-chamados");
    } catch (err: any) {
      setError(err.message || "Erro ao fazer login");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-background relative overflow-hidden">
      <div className="absolute top-0 left-0 w-full h-full greek-pattern-bg opacity-30 pointer-events-none"></div>
      <div className="absolute top-[-20%] right-[-10%] w-[50%] h-[50%] bg-secondary/10 rounded-full blur-[120px] pointer-events-none"></div>
      <div className="absolute bottom-[-20%] left-[-10%] w-[50%] h-[50%] bg-primary/10 rounded-full blur-[120px] pointer-events-none"></div>

      <Card className="w-full max-w-md relative z-10 border-secondary/20">
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary via-secondary to-primary rounded-t-md"></div>
        <CardHeader className="text-center pt-10 pb-6">
          <div className="mx-auto w-16 h-16 bg-primary rounded-md flex items-center justify-center mb-6 shadow-lg shadow-primary/20 transform -rotate-3">
            <ShieldCheck className="w-8 h-8 text-secondary transform rotate-3" />
          </div>
          <h1 className="text-4xl font-display font-bold text-foreground mb-2" data-testid="text-app-name">Hermes</h1>
          <p className="text-sm text-muted-foreground tracking-widest uppercase font-semibold">Suporte de TI com IA</p>
        </CardHeader>
        <CardContent className="px-10 pb-10">
          <form onSubmit={handleLogin} className="space-y-6">
            {error && (
              <div className="text-sm text-destructive bg-destructive/10 px-3 py-2 rounded-md border border-destructive/20" data-testid="text-login-error">
                {error}
              </div>
            )}
            <div className="space-y-2">
              <Label htmlFor="email" className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">E-mail</Label>
              <Input
                id="email"
                type="email"
                placeholder="seu@email.com"
                value={email}
                onChange={e => setEmail(e.target.value)}
                className="h-12 border-border/50 bg-background/50 focus-visible:ring-secondary focus-visible:border-secondary"
                data-testid="input-email"
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password" className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">Senha</Label>
              <Input
                id="password"
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={e => setPassword(e.target.value)}
                className="h-12 border-border/50 bg-background/50 focus-visible:ring-secondary focus-visible:border-secondary"
                data-testid="input-password"
                required
              />
            </div>
            <Button type="submit" className="w-full h-12 font-semibold tracking-wide" disabled={loading} data-testid="button-login">
              {loading ? "Entrando..." : "Entrar"}
            </Button>
          </form>
          <p className="text-center text-sm text-muted-foreground mt-6">
            Não tem conta?{" "}
            <Link href="/cadastro" className="text-secondary font-semibold" data-testid="link-register">Cadastre-se</Link>
          </p>
          <div className="mt-6 pt-4 border-t border-border/30 text-xs text-muted-foreground space-y-1">
            <p className="font-semibold text-center mb-2">Credenciais de teste:</p>
            <p>Admin: <span className="font-mono">admin@hermes.io</span> / <span className="font-mono">hermes123</span></p>
            <p>Usuário: <span className="font-mono">joao@empresa.com</span> / <span className="font-mono">senha123</span></p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
