// submissions/aluisio-junior/solution/frontend/src/pages/Login.tsx
import { useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Activity, Loader2 } from "lucide-react";

const Login = () => {
  const { login, signup } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [info, setInfo] = useState("");
  const [loading, setLoading] = useState(false);
  const [isSignUp, setIsSignUp] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setInfo("");
    setLoading(true);

    if (isSignUp) {
      const { error: err } = await signup(email, password);
      if (err) {
        setError(err);
      } else {
        setInfo("Conta criada! Verifique seu email para confirmar o cadastro.");
      }
    } else {
      const { error: err } = await login(email, password);
      if (err) {
        setError("Credenciais inválidas");
      } else {
        navigate("/");
      }
    }
    setLoading(false);
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-background px-4">
      <div className="w-full max-w-sm animate-fade-in">
        <div className="flex items-center justify-center gap-2 mb-8">
          <Activity className="h-8 w-8 text-primary" />
          <h1 className="text-2xl font-bold tracking-tight">Churn Intelligence</h1>
        </div>

        <div className="glass-card p-8">
          <h2 className="text-lg font-semibold mb-1">
            {isSignUp ? "Criar Conta" : "Entrar"}
          </h2>
          <p className="text-sm text-muted-foreground mb-6">
            {isSignUp
              ? "Cadastre-se para acessar o painel"
              : "Acesse o painel de análise de churn"}
          </p>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="seu@email.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Senha</Label>
              <Input
                id="password"
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                minLength={6}
              />
            </div>

            {error && <p className="text-sm text-destructive">{error}</p>}
            {info && <p className="text-sm text-primary">{info}</p>}

            <Button type="submit" className="w-full" disabled={loading}>
              {loading && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              {isSignUp ? "Cadastrar" : "Entrar"}
            </Button>
          </form>

          <div className="mt-6 pt-4 border-t border-border">
            <p className="text-xs text-muted-foreground text-center">
              {isSignUp ? "Já tem conta?" : "Não tem conta?"}{" "}
              <button
                type="button"
                className="text-primary hover:underline font-medium"
                onClick={() => {
                  setIsSignUp(!isSignUp);
                  setError("");
                  setInfo("");
                }}
              >
                {isSignUp ? "Entrar" : "Cadastrar"}
              </button>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;

// submissions/matheus-petrato/frontend/src/routes/(auth)/login/+page.svelte
<script lang="ts">
  import { api, setStoredToken, setStoredUser } from '$lib/services/api';

  let email = $state('');
  let password = $state('');
  let loading = $state(false);
  let errorMessage = $state('');

  async function handleLogin(e: Event) {
    e.preventDefault();
    loading = true;
    errorMessage = '';

    try {
      const data = await api.auth.login({ email, password });
      setStoredToken(data.token);
      setStoredUser(data.user);
      
      // Redirect to main app chat
      window.location.href = '/';
      
    } catch (err: any) {
      errorMessage = err.message || 'Erro ao conectar no servidor.';
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex flex-col animate-in fade-in slide-in-from-bottom-4 duration-500">
  <h1 class="text-[32px] mb-2 font-semibold tracking-tight text-foreground">Log in</h1>
  <p class="text-muted-foreground mb-8">Acesse com as credenciais enviadas por email.</p>

  {#if errorMessage}
    <div class="bg-red-500/10 border border-red-500/50 text-red-600 text-sm p-3 rounded-lg mb-4">
      {errorMessage}
    </div>
  {/if}

  <form class="flex flex-col gap-4" onsubmit={handleLogin}>
    <!-- Email -->
    <div class="space-y-1.5 flex flex-col">
      <label for="email" class="text-[14px] font-medium text-foreground">Email</label>
      <input id="email" type="email" bind:value={email} required placeholder="nome@empresa.com" class="w-full px-3 py-2.5 rounded-lg border border-border bg-background shadow-sm hover:border-primary/50 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all text-sm placeholder:text-muted-foreground/60" />
    </div>

    <!-- Password -->
    <div class="space-y-1.5 flex flex-col">
      <label for="password" class="text-[14px] font-medium text-foreground">Senha</label>
      <input id="password" type="password" bind:value={password} required placeholder="••••••••" class="w-full px-3 py-2.5 rounded-lg border border-border bg-background shadow-sm hover:border-primary/50 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all text-sm placeholder:text-muted-foreground/60" />
    </div>

    <!-- Options -->
    <div class="flex items-center justify-between mt-1 mb-2">
      <div class="flex items-center gap-2">
        <input type="checkbox" id="remember" class="rounded-[4px] border border-border text-primary focus:ring-1 focus:ring-primary/50 w-4 h-4 cursor-pointer accent-primary" />
        <label for="remember" class="text-sm text-foreground font-medium cursor-pointer">Lembrar por 30 dias</label>
      </div>
      <button type="button" class="text-sm font-semibold text-primary hover:text-primary/80 transition-colors">
        Esqueceu a senha?
      </button>
    </div>

    <button type="submit" disabled={loading} class="w-full py-2.5 rounded-lg bg-primary hover:bg-opacity-90 active:scale-[0.98] text-primary-foreground text-[15px] font-medium transition-all shadow-sm shadow-primary/30 mt-2 disabled:opacity-70 disabled:cursor-not-allowed">
      {loading ? 'Entrando...' : 'Entrar'}
    </button>
  </form>

  <p class="text-center text-sm text-muted-foreground mt-8">
    Precisa de acesso? <a href="mailto:help@g4compass.com" class="text-primary font-semibold hover:underline transition-colors">Fale com seu gestor</a>
  </p>
</div>
